name: naxerova_workshop
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bioconda::bwa
  - bioconda::gatk4
  - bioconda::samtools
  - conda-forge::git
  - conda-forge::r-base==4.4.2
  - conda-forge::r-ggplot2==3.5.2
  - bioconda::bioconductor-ggtree==3.14.0
  - conda-forge::r-ape
  - conda-forge::r-pheatmap
  - conda-forge::r-phytools
